### ISSUE TITLE
Disable raspi-config task fails. Do we need it at all?

### ISSUE THREAD

**Issue by mtju** [charleskorn/raspi-expanded-rootfs#5]
Currently this task fails since it can't find `fs_expanded.stat.exists` variable. I'm using Ansible 2.2.2.0 and a fresh copy of Raspbian GNU/Linux 8 (jessie).

I can't see a good reason why would we want to have this task? The role should work just fine without it.

**Comment by charleskorn** [comment]
Yep, you're correct - that was a leftover from before bc701801d3b2ff82b93e06bf1000194f183f2357 was merged. I'll fix that right now.

**Comment by charleskorn** [comment]
Fixed in 2b65407916c0eb5d033cade5d2e209180aff8775.
