### ISSUE TITLE
Handler for restart makes the restart to be done late in the process

### ISSUE THREAD

**Issue by smuda** [charleskorn/raspi-expanded-rootfs#9]
When using the role charleskorn.raspi-expanded-rootfs within a larger playbook, the handler for rebooting after changing the file system is done after all tasks has finished.

In my case that meant running out of free space before rebooting. I'd propose using a third task in 
tasks/main.yml:

```
- name: Reboot after file system change
  reboot:
  when: unpartitioned.stdout != "0.00GB"
```

Then the reboot will be automatically handled directly after changing the file system but only if it was changed. Of course the notification for the handlers in the previous task also will be removed.

If you want to, I can create a pull request.

**Comment by charleskorn** [comment]
Hi @smuda, thanks for the feedback. Your suggestion makes sense to me, however I don't have any time in the near future to implement it, so a pull request would be great!

**Comment by smuda** [comment]
@charleskorn Thank you for your really quick response and your module as a whole.
